### ISSUE TITLE
desktopAgent.findInstances keeps showing more instances on reload

### ISSUE THREAD

**Issue by bmaycc** [connectifi-co/fdc3-web-portal#32]
I have a connectifi desktop agent loaded in my app running on localhost.  When I start my app, after the createAgent passes, I run 

```
const instances = fdc3Agent.findInstances({
  appId: 'app-name'
});
console.log("INSTANCES", instances)
```

but upon every browser refresh (even after waiting a while), the instances list keeps growing.    Seems wrong?

**Comment by nkolba** [comment]
this one was fixed some time back...
